version: "3.7"

networks:
  web:
    external: true

volumes:
  cover-images:

services:
  api:
    image: reg.laravel.pt/api:${TAG}
    container_name: api
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.sidecar.laravel.pt`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.routers.api.tls.certresolver=leresolver"
    volumes:
    - ./.env:/var/www/html/.env
    - cover-images:/var/www/html/.env
