version: "3.7"

#

networks:
  web:
    external: true

volumes:
  cover_images:
  db_data:

services:
  backend:
    build:
      context: .
    restart: always
    networks:
      - web
    expose:
      - 80
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.api.rule=Host(`api.sidecar.laravel.pt`)"
      - "traefik.http.routers.backend.rule=Host(`api.sidecar.laravel.pt.test`)"
#      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
      - "traefik.http.routers.backend.service=backend"
#      - "traefik.http.routers.backend.tls.certresolver=leresolver"
    volumes:
    - ./.env:/var/www/html/.env
    - cover_images:/var/www/html/storage/app/cover_images

  postgres:
    image: postgres:13
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: laravel_portugal
    restart: always
    networks:
      - web

  redis:
    image: redis:6.0.9
    expose:
      - 6379
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - web
