openapi: 3.0.0
info:
  title: laravel-portugal/api
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/laravel-portugal/api/blob/master/LICENSE.md'
  description: API layer to support the public website of the Laravel-Portugal community
  contact:
    name: Developers
    url: 'https://github.com/laravel-portugal/api/issues'
servers:
  - url: 'https://api.laravel.pt'
    description: Production
  - description: Development
    url: 'http://api.laravel.test'
paths:
  /tags:
    get:
      summary: Your GET endpoint
      tags:
        - tags-domain
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Tag'
              examples: {}
      operationId: get-tags
      description: List all available tags
      parameters: []
components:
  schemas:
    Tag:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
          description: The resource's automatically generated unique identifier
        name:
          type: string
          minLength: 1
          description: The resource's submitted name
        created_at:
          type: string
          minLength: 1
          description: The resource's creation timestamp
        updated_at:
          type: string
          minLength: 1
          description: The resource's updated timestamp
        deleted_at:
          type: string
          minLength: 1
          description: The resource's deleted timestamp
      required:
        - name
  securitySchemes:
    User Credentials:
      type: oauth2
      flows:
        password:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
security: []
tags:
  - name: tags-domain
